if not DEFINED IS_MINIMIZED set IS_MINIMIZED=1 && start "" /min "%~dpnx0" %* && exit	w
"C:\Program Files\MATLAB\R2016b\bin\matlab.exe" -nodisplay -nosplash -nodesktop -r "run('C:\Users\Martin\Downloads\CASPR-master\CASPR-master\initialise_CASPR.m'), run('C:\Users\Martin\Downloads\CASPR-master\CASPR-master\scripts\local\GUI_script_autogenerated.m'), exit"
exit  
